In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("student_performance_10k.csv")

In [5]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement
0,1001,Aditya,20,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes
1,1002,Isha,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes
2,1003,Ananya,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes
3,1004,Diya,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No
4,1005,Dhruv,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No
9996,10997,Sanya,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No
9997,10998,Meera,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes
9998,10999,Rohan,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No
9999,11000,Dhruv,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes

In [6]:
df.head()

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement
0,1001,Aditya,20,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes
1,1002,Isha,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes
2,1003,Ananya,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes
3,1004,Diya,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No
4,1005,Dhruv,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No

In [7]:
df.tail()

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement
9995,10996,Riya,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No
9996,10997,Sanya,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No
9997,10998,Meera,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes
9998,10999,Rohan,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No
9999,11000,Dhruv,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes

In [8]:
df.describe()
df.info

<bound method DataFrame.info of       Student_ID    Name  Age  Gender        City  Course  Study_Hours  \
0           1001  Aditya   20    Male  Chandigarh  B.Tech          7.7
1           1002    Isha   22  Female       Delhi  M.Tech          8.8
2           1003  Ananya   19  Female       Solan    B.Sc          8.2
3           1004    Diya   22  Female      Mumbai     BCA          6.3
4           1005   Dhruv   23    Male       Noida     MCA          4.1
...          ...     ...  ...     ...         ...     ...          ...
9995       10996    Riya   21  Female      Jaipur  B.Tech          4.5
9996       10997   Sanya   21  Female       Solan  B.Tech          6.7
9997       10998   Meera   19  Female        Pune  B.Tech          8.0
9998       10999   Rohan   19    Male       Solan  B.Tech          6.2
9999       11000   Dhruv   22    Male    Gurugram  B.Tech          8.0

      Attendance  Assignments_Completed  Midterm_Score  Final_Score  Projects  \
0             88                     11             72           72         4
1             92                     18             81           81         4
2             88                     14             74           80         4
3             78                     13             68           64         2
4             73                      6             54           44         1
...          ...                    ...            ...          ...       ...
9995          72                     10             46           42         1
9996          87                     14             67           70         2
9997          87                     19             70           67         4
9998          83                     11             63           62         4
9999          84                     14             65           73         4

     Internship  Backlogs Placement
0           Yes         0       Yes
1           Yes         0       Yes
2           Yes         0       Yes
3            No         1        No
4            No         2        No
...         ...       ...       ...
9995         No         1        No
9996         No         0        No
9997         No         0       Yes
9998         No         1        No
9999         No         0       Yes

[10000 rows x 15 columns]>

In [9]:
df["Age"]

0       20
1       22
2       19
3       22
4       23
        ..
9995    21
9996    21
9997    19
9998    19
9999    22
Name: Age, Length: 10000, dtype: int64

In [10]:
# it is used to inspect the missig values in the dataset
df.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Gender                   0
City                     0
Course                   0
Study_Hours              0
Attendance               0
Assignments_Completed    0
Midterm_Score            0
Final_Score              0
Projects                 0
Internship               0
Backlogs                 0
Placement                0
dtype: int64

In [11]:
# selacting the rows and cloumns
df.iloc[22]

Student_ID                  1023
Name                     Krishna
Age                           20
Gender                      Male
City                       Delhi
Course                    B.Tech
Study_Hours                  7.3
Attendance                    79
Assignments_Completed         14
Midterm_Score                 65
Final_Score                   66
Projects                       3
Internship                   Yes
Backlogs                       0
Placement                    Yes
Name: 22, dtype: object

In [12]:
df.loc[22]

Student_ID                  1023
Name                     Krishna
Age                           20
Gender                      Male
City                       Delhi
Course                    B.Tech
Study_Hours                  7.3
Attendance                    79
Assignments_Completed         14
Midterm_Score                 65
Final_Score                   66
Projects                       3
Internship                   Yes
Backlogs                       0
Placement                    Yes
Name: 22, dtype: object

In [13]:
df["Gender"].value_counts()

Gender
Male      5310
Female    4690
Name: count, dtype: int64

In [14]:
df["Placement"].value_counts()

Placement
No     6200
Yes    3800
Name: count, dtype: int64

In [15]:
# understaning the unique values in the data sets
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [16]:
#unique() → shows the actual unique values
#nunique() → tells you how many unique values exist
df["Placement"].nunique()

2

In [17]:
df.isnull().any()

Student_ID               False
Name                     False
Age                      False
Gender                   False
City                     False
Course                   False
Study_Hours              False
Attendance               False
Assignments_Completed    False
Midterm_Score            False
Final_Score              False
Projects                 False
Internship               False
Backlogs                 False
Placement                False
dtype: bool

In [18]:
df.isnull().sum().sum()

np.int64(0)

In [19]:
df[df["Age"]==25]

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement
10,1011,Vansh,25,Male,Kolkata,MCA,8.6,89,16,79,75,4,No,0,Yes
63,1064,Aarav,25,Male,Jaipur,MCA,6.5,83,11,56,63,1,Yes,1,No
119,1120,Isha,25,Female,Mumbai,MCA,8.4,86,16,74,75,4,No,0,No
193,1194,Priya,25,Female,Mumbai,M.Tech,4.6,79,6,58,55,1,Yes,1,No
205,1206,Vansh,25,Male,Kolkata,MCA,5.5,84,11,59,48,3,No,1,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9932,10933,Kabir,25,Male,Shimla,M.Tech,3.6,68,7,45,40,2,No,1,No
9942,10943,Arjun,25,Male,Shimla,M.Tech,7.5,86,15,69,74,4,Yes,0,Yes
9957,10958,Anika,25,Female,Noida,M.Tech,5.4,80,8,62,57,4,Yes,0,No
9961,10962,Kavya,25,Female,Shimla,MCA,5.4,79,10,61,52,1,No,3,No
9966,10967,Anushka,25,Female,Chennai,MCA,6.8,83,11,65,64,1,No,0,No

In [20]:
#finding the duplicates in the datset
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [21]:
df[["Age" , "Placement"]]

      Age Placement
0      20       Yes
1      22       Yes
2      19       Yes
3      22        No
4      23        No
...   ...       ...
9995   21        No
9996   21        No
9997   19       Yes
9998   19        No
9999   22       Yes

[10000 rows x 2 columns]

In [22]:
df["AP"] = df["Age"] + df["Attendance"]

In [23]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP
0,1001,Aditya,20,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,Isha,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [24]:
df["AP"] + 1

0       109
1       115
2       108
3       101
4        97
       ...
9995     94
9996    109
9997    107
9998    103
9999    107
Name: AP, Length: 10000, dtype: int64

In [25]:
df.rename(  columns = {"AP" : "AP12"},
        #inplace= False  
        inplace=True)

In [26]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
0,1001,Aditya,20,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,Isha,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [27]:
df.drop("Name", axis=1)

,Student_ID,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
0,1001,20,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [28]:
df.drop(0,axis=0)

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
1,1002,Isha,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
5,1006,Krishna,19,Male,Chennai,B.Sc,7.0,83,14,67,68,4,Yes,0,No,102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [29]:
df.sort_values("Age")

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
3278,4279,Krishna,18,Male,Shimla,B.Sc,5.4,78,13,53,53,2,No,1,No,96
55,1056,Ananya,18,Female,Delhi,BCA,6.1,78,11,69,68,3,No,0,No,96
58,1059,Ayaan,18,Male,Ahmedabad,B.Sc,7.7,88,14,80,78,4,No,0,Yes,106
67,1068,Sanya,18,Female,Pune,B.Sc,6.8,80,12,64,58,4,No,0,No,98
9931,10932,Dhruv,18,Male,Pune,B.Tech,8.6,92,17,88,79,5,No,0,Yes,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8728,9729,Kabir,25,Male,Chandigarh,M.Tech,8.2,88,17,74,73,5,No,1,No,113
2384,3385,Dhruv,25,Male,Bangalore,M.Tech,5.8,80,10,62,59,3,No,2,Yes,105
8158,9159,Arjun,25,Male,Chandigarh,M.Tech,4.1,69,8,44,43,2,No,4,No,94
9932,10933,Kabir,25,Male,Shimla,M.Tech,3.6,68,7,45,40,2,No,1,No,93
6615,7616,Neha,25,Female,Jaipur,M.Tech,6.7,86,10,70,63,3,No,0,No,111

In [30]:
df["Gender"].replace( {
    "Male" : "M",
    "Female" : "F"
}
)

0       M
1       F
2       F
3       F
4       M
       ..
9995    F
9996    F
9997    F
9998    M
9999    M
Name: Gender, Length: 10000, dtype: object

In [31]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
0,1001,Aditya,20,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,Isha,22,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,19,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,22,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,23,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,21,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,21,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,19,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,19,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,22,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [32]:
df["Age"] = df["Age"].apply(lambda x: x + 1)

In [33]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
0,1001,Aditya,21,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,Isha,23,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,20,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,23,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,24,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,22,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,22,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,20,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,20,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,23,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [34]:
df.groupby("Gender")["Final_Score"].mean()

Gender
Female    62.385288
Male      61.941431
Name: Final_Score, dtype: float64

In [35]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
0,1001,Aditya,21,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,Isha,23,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,20,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,23,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,24,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,22,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,22,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,20,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,20,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,23,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [43]:
x = df[["Age" , "Study_Hours" , "Attendance"]]
y = df[["Placement"]]

In [44]:
x

      Age  Study_Hours  Attendance
0      21          7.7          88
1      23          8.8          92
2      20          8.2          88
3      23          6.3          78
4      24          4.1          73
...   ...          ...         ...
9995   22          4.5          72
9996   22          6.7          87
9997   20          8.0          87
9998   20          6.2          83
9999   23          8.0          84

[10000 rows x 3 columns]

In [45]:
y

     Placement
0          Yes
1          Yes
2          Yes
3           No
4           No
...        ...
9995        No
9996        No
9997       Yes
9998        No
9999       Yes

[10000 rows x 1 columns]

                                                                   || ONE HOT ENCODING ||

In [ ]:
pd.get_dummies(df["Gender"])

      Female   Male
0      False   True
1       True  False
2       True  False
3       True  False
4      False   True
...      ...    ...
9995    True  False
9996    True  False
9997    True  False
9998   False   True
9999   False   True

[10000 rows x 2 columns]

In [47]:
df

,Student_ID,Name,Age,Gender,City,Course,Study_Hours,Attendance,Assignments_Completed,Midterm_Score,Final_Score,Projects,Internship,Backlogs,Placement,AP12
0,1001,Aditya,21,Male,Chandigarh,B.Tech,7.7,88,11,72,72,4,Yes,0,Yes,108
1,1002,Isha,23,Female,Delhi,M.Tech,8.8,92,18,81,81,4,Yes,0,Yes,114
2,1003,Ananya,20,Female,Solan,B.Sc,8.2,88,14,74,80,4,Yes,0,Yes,107
3,1004,Diya,23,Female,Mumbai,BCA,6.3,78,13,68,64,2,No,1,No,100
4,1005,Dhruv,24,Male,Noida,MCA,4.1,73,6,54,44,1,No,2,No,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,10996,Riya,22,Female,Jaipur,B.Tech,4.5,72,10,46,42,1,No,1,No,93
9996,10997,Sanya,22,Female,Solan,B.Tech,6.7,87,14,67,70,2,No,0,No,108
9997,10998,Meera,20,Female,Pune,B.Tech,8.0,87,19,70,67,4,No,0,Yes,106
9998,10999,Rohan,20,Male,Solan,B.Tech,6.2,83,11,63,62,4,No,1,No,102
9999,11000,Dhruv,23,Male,Gurugram,B.Tech,8.0,84,14,65,73,4,No,0,Yes,106

In [48]:
df = pd.DataFrame({
    "Age": [20, 22, 19],
    "Gender": ["Male", "Female", "Female"]
})

encoded_df = pd.get_dummies(df)

print(encoded_df)

   Age  Gender_Female  Gender_Male
0   20          False         True
1   22           True        False
2   19           True        False

In [49]:
encoded_df = pd.get_dummies(df, dtype=int)
print(encoded_df)

   Age  Gender_Female  Gender_Male
0   20              0            1
1   22              1            0
2   19              1            0

In [54]:
pd.get_dummies(df["Gender"] , dtype=int)

   Female  Male
0       0     1
1       1     0
2       1     0

In [56]:
print(df.columns)

Index(['Age', 'Gender'], dtype='object')

In [61]:
sdf = pd.read_csv("student_performance_10k.csv")

In [62]:
sdf["Placement"]

0       Yes
1       Yes
2       Yes
3        No
4        No
       ...
9995     No
9996     No
9997    Yes
9998     No
9999    Yes
Name: Placement, Length: 10000, dtype: object

In [63]:
pd.get_dummies(sdf["Placement"] , dtype=int)

      No  Yes
0      0    1
1      0    1
2      0    1
3      1    0
4      1    0
...   ..  ...
9995   1    0
9996   1    0
9997   0    1
9998   1    0
9999   0    1

[10000 rows x 2 columns]

                                          ||    ////////////////////////////////////     ||